image = {"escritorio": "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\1-OFFICE.png",
		 "ventilador": "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\FAN\\1.png"}

botoes_esquerdos_pressionados = {
	"nenhum": "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\LEFT\\1-STOPPED.png",
	"porta" : "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\LEFT\\2-DOOR.png",
	"luz"   : "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\LEFT\\3-LIGHT.png",
	"ambos" : "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\LEFT\\4-BOTH.png"
}

botoes_direitos_pressionados = {
	"nenhum": "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\RIGHT\\1-STOPPED.png",
	"porta" : "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\RIGHT\\2-DOOR.png",
	"luz"   : "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\RIGHT\\3-LIGHT.png",
	"ambos" : "FNAF ASSETS REORGANIZED BY ENTEREST\\3-THE_OFFICE\\DOORS\\BUTTONS\\RIGHT\\4-BOTH.png"
}
